= Application reference --- sample placeholder
:example-caption!:Application Reference Template

This is just a template for application reference information.

*Eventually, each application will have a reference guide*



== Getting Started


ssssss


== Code samples

ddddd

== API Reference

dddddd







== Basic formatting Guide

You can add the following inline styles to your content:

* Steps
* Bold
* Italic
* Monospace
* Highlight

=== Bold and italic

You can bold and italic entire phrases, a word, and characters in a word.

.Bold and italic inline formatting
----
*bold phrase* & **char**acter**s**

_italic phrase_ & __char__acter__s__

*_bold italic phrase_* & **__char__**acter**__s__**
----

.Result
====
*bold phrase* & **char**acter**s**

_italic phrase_ & __char__acter__s__

*_bold italic phrase_* & **__char__**acter**__s__**
====

=== Monospace

You can monospace entire phrases, a word, and characters in a word.

.Monospace inline formatting
----
`monospace phrase` & ``char``acter``s``

`*monospace bold phrase*` & ``**char**``acter``**s**``

`_monospace italic phrase_` & ``__char__``acter``__s__``

`*_monospace bold italic phrase_*` &
``**__char__**``acter``**__s__**``
----

.Result
====
`monospace phrase` & ``char``acter``s``

`*monospace bold phrase*` & ``**char**``acter``**s**``

`_monospace italic phrase_` & ``__char__``acter``__s__``

`*_monospace bold italic phrase_*` &
``**__char__**``acter``**__s__**``
====

=== Highlight

You can highlight entire phrases, a word, and characters in a word.

.Highlight inline formatting
----
Let's #highlight this phrase# and part of th##is##.
----

.Result
====
Let's #highlight this phrase# and part of th##is##.
====
